### ISSUE TITLE
Get CharLSTM Entity Level Sentiment to Work

### ISSUE THREAD

**Issue by demongolem** [demongolem/MultilevelSentiment#5]
I am not sure of the status of this combination, but I have mostly focused on document level and somewhat focused on sentence level, so check out, report back and fix if necessary this combination

**Comment by demongolem** [comment]
Document and sentence seem to work with little trouble on smaller documents.  When we shift to entity level analysis, we run into much slower execution and frequent OutOfMemory traces such as this one:

> Exception in thread "Thread-3" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.ArrayList.iterator(ArrayList.java:840)
	at sun.nio.ch.WindowsSelectorImpl.updateSelectedKeys(WindowsSelectorImpl.java:496)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:172)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	at sun.nio.ch.SelectorImpl.selectNow(SelectorImpl.java:105)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:408)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-7" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at java.io.ObjectInputStream$BlockDataInputStream.readUTFBody(ObjectInputStream.java:3429)
	at java.io.ObjectInputStream$BlockDataInputStream.readUTF(ObjectInputStream.java:3224)
	at java.io.ObjectInputStream.readString(ObjectInputStream.java:1903)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1562)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at java.util.HashMap.readObject(HashMap.java:1407)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1158)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2176)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2067)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1571)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2285)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2209)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2067)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1571)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2285)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2209)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2067)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1571)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at edu.stanford.nlp.io.IOUtils.readObjectFromURLOrClasspathOrFileSystem(IOUtils.java:309)
	at edu.stanford.nlp.parser.common.ParserGrammar.loadModel(ParserGrammar.java:184)
	at edu.stanford.nlp.pipeline.ParserAnnotator.loadModel(ParserAnnotator.java:219)
	at edu.stanford.nlp.pipeline.ParserAnnotator.<init>(ParserAnnotator.java:121)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.parse(AnnotatorImplementations.java:113)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$50(StanfordCoreNLP.java:552)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP$$Lambda$33/66183959.apply(Unknown Source)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$null$69(StanfordCoreNLP.java:625)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP$$Lambda$52/1828860435.get(Unknown Source)
